### ISSUE TITLE
Warning for spaces

### ISSUE THREAD

**Issue by Osmosis311** [ajacksified/hubot-plusplus#56]
You get a warning via Slackbot if you include spaces between a user's name and the ++ or --, however, when you select a user from the auto-complete list in slack, it automatically adds a colon and a space.  It's unrealistic to expect people are going to hit backspace 3 times before adding ++ or --.

**Comment by therealklanni** [comment]
Can you clarify? I have no problem using `@username: ++ for stuff` syntax on the latest version.

**Comment by therealklanni** [comment]
Closing until we get further clarification.
