### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by fuadsaud** [ajacksified/hubot-plusplus#72]
Would it be viable to have support for multiple languages when adding a reason for the points?

It'd be nice to be able to do something like: `foo++ por <insert reason>`. `por` is the Portuguese word for `for`. I understand that it might not be interesting to keep a list of conjunctions for every single language out there, but maybe it's possible to insert some flexibility. What do you think?

**Comment by therealklanni** [comment]
We could make it configurable through an env var. PRs welcomed!

**Comment by fuadsaud** [comment]
I finally got some time to work on this. Should I make a PR to this repo? I didn't get the note in the README pointing to hubot-scripts repo.
