### ISSUE TITLE
modify script of adding more than 1 point

### ISSUE THREAD

**Issue by jy2008** [ajacksified/hubot-plusplus#76]
Hi I previously inquired about if this can add more than 1 point and you answered 'No', i have a follow up question: Is it a lot work to modify it to have it add more than 1 point? 

I have no experience at all on coffee script, if i am going to modify it, what community or document you would recommend me to have for help and support?

Thanks

**Comment by therealklanni** [comment]
It's just not the intent of this script. The intent is to only ever change by 1 or -1 at a time. It's possible there are other scripts that fit the behavior you're wanting.

**Comment by jy2008** [comment]
thank you. I searched, none such scripts exists. I guess i will have to learn how to modify it.
