### ISSUE TITLE
Characters after the command don't cause a match

### ISSUE THREAD

**Issue by strugee** [ajacksified/hubot-plusplus#80]
In IRC, this:

> evanpro++ :D

doesn't trigger this module, but this:

> evanpro++

does. Not critical by any stretch of the imagination, but I thought I'd capture it in an issue for posterity.

Thanks for maintaining this module <3

**Comment by ajacksified** [comment]
That's by design, so you don't turn "I really love using C++ and Javascript" into "I really love using C has 1 points". You can use reasons, such as "evanpro++ for :D".

**Comment by strugee** [comment]
Hm, interesting. So the expected behavior I was thinking of was that for the string `evanpro++ :D`, `evanpro` would get 1 point for no reason. I.e. the `:D` would just be ignored since it didn't have `for` or `because` or whatever.

`C++` is tricky though...
